server:
  port: 8081

girl :
  age : 21
  cupSize : B
spring:
  datasource:
    url:
    username: testadmin
    password: test123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initialSize : 5
    minIdle : 5
    maxActive : 20
    ## 配置获取连接等待超时的时间
    maxWait : 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
  #集成redis
  redis :
      host :
      port : 6379
      password : 123456
      poolMaxIdle : 100
      poolMaxTotal : 80
      poolMaxWait : 3000
      poolMaxActive : 100
      #超时时间是ms
      timeout : 50
      numTestsPerEvictionRun : 1024
      timeBetweenEvictionRunsMillis : 30000
      minEvictableIdleTimeMillis : 1800000
      softMinEvictableIdleTimeMillis : 10000
      testOnBorrow : true
      testWhileIdle : true
      blockWhenExhausted : false

mybatis :
  #config : classpath:mybatis-config.xml
  mapperLocations : classpath:mappers/*.xml
  type-aliases-package: com.springboot.girl.bean
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#指定输出执行SQL的DAO包路径名
logging:
  level:
    com :
      springboot :
        girl :
          mapper : debug